#!/bin/bash

# This is the ffmpeg command that the audio shortcut in i3 will run

if [[ -f ~/output.flac ]]
    then
        n=1
        while [[ -f ~/output_$n.flac ]]
        do
            n=$(qalc -t $n + 1)
        done
        filename="output_$n.flac"
        echo $n
    else
        filename="output.flac"
fi

# The actual ffmpeg command:

ffmpeg \
-f alsa -i default \
-c:a flac \
$filename
